name: Linux

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Head Repo URL Environment Variable
      if: github.event_name == 'pull_request' 
      run: |
        echo "HEAD_REPO_URL=${{ github.event.pull_request.head.repo.clone_url }}" >> $GITHUB_ENV
        echo "COMMIT=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        echo "BRANCH=NONE" >> $GITHUB_ENV
    - name: Build
      run: ./src/scripts/build.sh
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: friction-ci-linux-x86_64
        path: distfiles/builds/*/*.AppImage
