name: macOS (arm64)

on: [push, pull_request]

jobs:
  release:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: ./src/scripts/build_mac_ci.sh
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: friction-ci-macOS-arm64
        path: build-release/*.dmg
