name: macOS

on:
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: macos-15
    steps:
    - name: Configure git credentials
      run: git config --global credential.helper ""
    - uses: actions/checkout@v4
    - name: Cache SDK
      uses: actions/cache@v4
      with:
        path: sdk
        key: friction-sdk-1.0.0r5-macOS
    - name: Build
      env:
        GHA_RUN_NUMBER: ${{ github.run_number }}
        BUILD_ORIGIN: ci
      run: ./src/scripts/build_mac_ci.sh
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: friction-macOS-${{ github.sha }}
        path: build-release-universal/*.dmg
