name: macOS (x86_64)

on: workflow_dispatch

jobs:
  release:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: ./src/scripts/build_mac_ci.sh
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: friction-ci-macOS-x86_64
        path: build-release/*.dmg
