name: Windows

on: workflow_dispatch

jobs:
  release:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: cmd
      run: .\src\scripts\build.bat ci
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: friction-ci-windows-x64
        path: |
          build\output\friction-*.7z
          build\output\friction-*.exe
